"""The SQL dialect seam.

Every place the two engines disagree — parameter markers, date functions,
upsert syntax, generated keys, introspection — is declared here once, so query
code never contains `if driver == "postgres"`.

Adding an engine means adding one module and one registry entry.
"""

from abc import ABC, abstractmethod


class Dialect(ABC):
    name = ""
    placeholder = "?"
    timestamp_type = "DATETIME"
    serial_pk = "INTEGER PRIMARY KEY AUTOINCREMENT"

    def placeholders(self, count):
        return ", ".join([self.placeholder] * count)

    # -- expressions ---------------------------------------------------------

    @abstractmethod
    def hour_of(self, column, tz):
        """Integer local hour 0-23 for IANA timezone `tz`."""

    @abstractmethod
    def weekday_name_of(self, column, tz):
        """Full local weekday name for IANA timezone `tz`."""

    @abstractmethod
    def local_date(self, column, tz):
        """Local calendar date (YYYY-MM-DD) for IANA timezone `tz`."""

    @abstractmethod
    def local_week_start(self, column, tz):
        """Local Sunday starting the week containing `column` in `tz`."""

    @abstractmethod
    def local_month_start(self, column, tz):
        """Local first-of-month date for `column` in `tz`."""

    @abstractmethod
    def within_last_days(self, column, days):
        """Predicate fragment limiting a column to the last N days."""

    @abstractmethod
    def since_start_of_year(self, column):
        """Predicate fragment limiting a column to the current year."""

    # -- statements ----------------------------------------------------------

    @abstractmethod
    def insert_ignore(self, table, columns, conflict):
        """INSERT that silently skips rows already present."""

    @abstractmethod
    def upsert(self, table, columns, conflict, updates):
        """INSERT that overwrites `updates` when `conflict` already exists."""

    @abstractmethod
    def insert_returning_id(self, table, columns):
        """INSERT whose generated key is readable via `inserted_id`."""

    @abstractmethod
    def inserted_id(self, cursor):
        """The key generated by the last `insert_returning_id` execution."""

    @abstractmethod
    def existing_columns(self, cursor, table):
        """Column names currently on a table, for additive migrations."""
